site:
  name: Casa Vacanze Ianes
  site: 'https://yourdomain.com'
  base: '/'
  trailingSlash: false

  # googleSiteVerificationId: your-verification-id

# Default SEO metadata
metadata:
  title:
    default: Casa Vacanze Ianes
    template: '%s â€” Casa Vacanze Ianes'
  description: "Vacation rentals for your perfect getaway"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Casa Vacanze Ianes
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@yourproperty'
    site: '@yourproperty'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: false
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # Add your Google Analytics ID here, e.g., "G-XXXXXXXXXX"

ui:
  theme: 'light' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
